### ISSUE TITLE
Version detection issues

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#101]
**Badly formed version tag fails ugly**
If the version tag is not formatted correctly, the build compiles most everything and then fails.
Should fail immediately and say why.

**Multiple tags not detected**
If the current tip has multiple tags, not clear which one is fetched.  If one is badly formatted, build may fail even though valid tag is present.

**Comment by tanaya-bigladder** [comment]
Does "not formatted correctly" correspond to an error in grabbing the Git SHA/branch/tag?

**Comment by nealkruis** [comment]
Yeah, this is something that I would like to generalize for Atheneum type projects too. There are a couple of tasks here:

1. Instead of giving up and assigning "?.?.?" as the version number, CMake should probably fail.
2. The regular expressions need to be able to capture other build meta data from a tag too ([per semantic versioning](https://semver.org/#spec-item-10)). I think this will fail the pattern recognition.

**Comment by tanaya-bigladder** [comment]
To rephrase my question, if I want to reproduce the build failure, what do I need to make fail? Does "not formatted correctly" usually mean that the `git rev-parse` failed?

**Comment by tanaya-bigladder** [comment]
Opened PR #202
