### ISSUE TITLE
Possible character limit for report/export file names (rfFileName & xfFileName)

### ISSUE THREAD

**Issue by aaron-boranian** [cse-sim/cse#194]
For a large-scale parametric project using CSE, I was attempting to generate export files in a directory named *csv_results* with different frequencies of output data:

- `Batteryyr`: annual (one CSV that appends a row for each case simulated)
- `BattDay`: daily (one CSV for each case)
- `BattHr`: hourly (one CSV for each case)

Below are the EXPORTFILE object definitions:
```
EXPORTFILE "Batteryyr" xfFileName="..\\..\\..\\csv_results\\Batteryyr.csv"  xfFileStat=Append
EXPORTFILE "BattDay"   xfFileName="..\\..\\..\\csv_results\\BattDay_3BR_3BRp_2022_0kW_40kWh_TOUstart10AM-CZ01.csv"   // Goes into the mtr export
EXPORTFILE "BattHr"    xfFileName="..\\..\\..\\csv_results\\BattHr_CZ01_3BR_3BRp_2022_0kW_40kWh_TOUstart10AM.csv"   // Goes into the mtr export
```

Each of these are supposed to write to the same folder, but only the last two throw errors that stop the simulation:
```
Error on line 45:   exportFile 'BattDay': 
    bad file name '..\..\..\CSV-RESULTS\BATTDAY_3BR_3BRP_2022_0KW_40KWH_TOUSTART10AM-CZ01.CSV' -- No such file or directory (SEC=2)

Error on line 57:   exportFile 'BattHr': 
    bad file name '..\..\..\CSV-RESULTS\BATTHR_CZ01_3BR_3BRP_2022_0KW_40KWH_TOUSTART10AM.CSV' -- No such file or directory (SEC=2)
```

Here are a few things that I tried:
1. Defining all options for `xfFileStat` (New, Overwrite, Append) for the last 2 EXPORTFILEs. This did not work.
2. Shortening the file name **WORKED**. 
3. Replacing `csv_results` with `..` to write the CSVs in the folder one level above **WORKED**.
4. Removing all `..` to write CSVs in same folder as CSE input file **WORKED**. 

The last test especially leads me to believe it's not a full path issue of Windows OS or CSE but a filename issue of CSE.
Windows OS are supposed to have [260-character limit on full path](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd), and the full path had ~240 characters for both working EXPORTFILEs in test #4 (full paths below).

```
C:\projects\wilcox\res-sf-prototypes\modelkit\analysis\2022_standalone_tou_batt\csv_results\BATTDAY_3BR_3BRP_2022_0KW_40KWH_TOUSTART10AM.CSV

C:\projects\wilcox\res-sf-prototypes\modelkit\analysis\2022_standalone_tou_batt\csv_results\BATTHR_CZ01_3BR_3BRP_2022_0KW_40KWH_TOUSTART10AM.CSV
```

Attaching the following files to help reproduce the bug:

- CSE input file (TXT file with name ending in "_CSE", Github won't allow attaching .cse files)
- CSV of hourly TDV multipliers
- TXT include file defining the EXPORTFILE content
- EPW weather file (TXT file with name ending in "_EPW", Github won't allow attaching .epw files)
- DHW draw TXT file
- Error file from CSE (TXT file with name ending in "_ERR", Github won't allow attaching .err files)

[3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01 - Prop_CSE.txt](https://github.com/cse-sim/cse/files/8381820/3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01.-.Prop_CSE.txt)
[3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01 - Prop_ERR.txt](https://github.com/cse-sim/cse/files/8381822/3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01.-.Prop_ERR.txt)
[3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01.txt](https://github.com/cse-sim/cse/files/8381823/3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01.txt)
[CA_ARCATA-AP_725945S_STYP20_EPW.txt](https://github.com/cse-sim/cse/files/8381824/CA_ARCATA-AP_725945S_STYP20_EPW.txt)
[DHWDU2.txt](https://github.com/cse-sim/cse/files/8381825/DHWDU2.txt)
[3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01 - Prop-tdv.csv](https://github.com/cse-sim/cse/files/8382906/3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01.-.Prop-tdv.csv)

**Comment by tanaya-bigladder** [comment]
@aaron-boranian is there any chance you can upload the project files so that we could reproduce the bug? Or is it huge?

**Comment by aaron-boranian** [comment]
@tanaya-bigladder sure thing, I've just updated the post with links to project files. I did have to change file types for some due to Github's file type limitations, so let me know if reverting the CSE, EPW, or ERR files from TXT format doesn't work.

**Comment by tanaya-bigladder** [comment]
Looks like I also need "3BR_3BRp_2022_0kW_13.5kWh_TOUstart10AM-CZ01 - Prop-tdv.csv". :)

**Comment by aaron-boranian** [comment]
@tanaya-bigladder d'oh! Just updated the issue and added that missing file.

**Comment by nealkruis** [comment]
@galanCA I would like to raise the priority of this issue. We came across a similar issue (possibly the same issue?) that is likely related to path length. I am attaching those files here. My suspicion is that the working directory path may need to be very long to trigger the error.

[MF8Unit-CSE910bug.zip](https://github.com/cse-sim/cse/files/10374988/MF8Unit-CSE910bug.zip)

**Comment by galanCA** [comment]
The issue is related to giving a relative path to xfFileName in EXPORTFILE object, when given, CSE does not use the location of `Input file path` but instead the location of the build source file. The logic can be found in [cncult4.cpp L1202](https://github.com/cse-sim/cse/blob/5adeb8781756cab039531513837e84abc0da2150/src/cncult4.cpp#L1200-L1202).

**Comment by nealkruis** [comment]
Good find, @galanCA!

I think there are two reasonable options for relative paths of export/report files:

1. relative to the input file directory
2. relative to the current working directory

@chipbarnaby, I know sometime CSE looks in other locations (e.g., relative to the executable--but it's hard to imagine a user wanting for exports/reports). Are there other locations we should consider?

The current behavior is a mix of the two: It's relative to the input file directory if the input does not include a directory (or a drive letter), and it's relative to the current working directory otherwise.

I suspect most users want to make it relative to the input file directory. We could:

1. always make that the case, or
2. add an input to make them relative to the current working directory

**Comment by chipbarnaby** [comment]
I did a little experimenting.  The relative path is being applied to the
cwd as Neal said. Cwd apparently never changed during the session (?).
hello() saves the cwd and byebye() restores it, but I could not find
anything that alters it.  Anyone know of anything that changes cwd?

So the code that Cesar pointed out interprets the ".." as a directory and
does NOT apply InputDirPath.  That means the path is relative to the cwd
which is the directory from which cse was invoked.

Given that virtually everything else keys off of the input file location, I
am thinking we should do that here.  Do we have a way to determine if a
path is relative or absolute?  If relative, InputDirPath should be
pre-pended, I think.

I did not test what happens when the input file is located via a path
search.  But I think the idea is that the input file is the anchor and we
should stick to that, no matter how it is located.

Also, I propose that this logic gets extracted to a function (perhaps in
xiopak?).

However this shakes out, I think we should move the logic to a function (in
xiopak?), rather than having it local as seen here.
