### ISSUE TITLE
Intermittent regression test difference -- "-0" vs "-1"

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#213]
The attached file fails regression test compare intermittently.

What is known --
* Differences are only for "-0" vs "-1".
* Differences to date have only been seen for a single report at a single time (Dec. 3, hr 5, subr 1).
* With trap code active in cvpak.cpp (release build) (see notes there), the inconsistent behavior was not seen.
* When "coldec=0" is changed to "coldec=3" on the report column in question (qBal2), the problem not seen even with many attempts.

See cvpak.cpp, search for M0BUG.

Attached files --
wshp.cse   CSE file exhibiting issue
wshp_1.rep   Output from one run
wshp_2.rep   Output from another run (differs)
wshp_ok.cse   colDec=0 changed to colDec=3 on column qBal2
wshp_ok.rep   Output from  wshp_ok.cse

[wshpex.zip](https://github.com/cse-sim/cse/files/8405097/wshpex.zip)

**Comment by tanaya-bigladder** [comment]
Some questions, @chipbarnaby:

I get the following errors when I run SHA 7b500e0b with your wshp.cse input file, could you help me resolve them?

```
Command line: .\wshp.cse
  Z:\Projects\CSE_issue_213\wshpex\wshp.cse run 001: Input
---------------
  rsType = WSHP
           ^
Z:\PROJECTS\CSE_ISSUE_213\WSHPEX\WSHP.CSE(2087): Error:
  S0020: V0039: 'WSHP' is not one of ACFurnace ACResistance ACPkgRoom
    ACPkgRoomFurnace ACPkgRoomResistance ASHP ASHPHydronic ASHPPkgRoom
    VCHP2 AC Furnace Resistance FanCoil
    (OR mispelled word or omitted quotes)
---------------
Z:\PROJECTS\CSE_ISSUE_213\WSHPEX\WSHP.CSE(2085): Error: RSYS 'rsys1':
    S0496: Can't give 'rsCapAuxH' when rsType is not ASHP, ASHPHydronic, ASHPPkgRoom, or VCHP2
---------------
Z:\PROJECTS\CSE_ISSUE_213\WSHPEX\WSHP.CSE(2085): Error: RSYS 'rsys1':
    S0496: Can't give 'rsCOP47' when rsType is not ASHP, ASHPHydronic, ASHPPkgRoom, or ASHPVC (VCHP2)
---------------
Z:\PROJECTS\CSE_ISSUE_213\WSHPEX\WSHP.CSE(2085): Error:
  RSYS 'rsys1': S0497: 'rsSEER' missing: required when rsType=ACFurnace
---------------
Z:\PROJECTS\CSE_ISSUE_213\WSHPEX\WSHP.CSE(2461): Info:
  S0214: No run due to error(s) above
---------------
```

**Comment by nealkruis** [comment]
@tanaya-bigladder, you'll have to test on the `wshp` branch.

**Comment by tanaya-bigladder** [comment]
When I define `M0BUG` to reproduce the error, the linker complains:
```
CVPAK.obj : error LNK2001: unresolved external symbol "class TOPRAT Top" (?Top@@3VTOPRAT@@A) [C:\Users\Tanaya Mankad\source\repos\cse\msvc\build\src\RCDEF\RCDEF.vcxproj]
C:\Users\Tanaya Mankad\source\repos\cse\msvc\build\src\RCDEF\Release\RCDEF.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\Tanaya Mankad\source\repos\cse\msvc\build\src\RCDEF\RCDEF.vcxproj]
```

**Comment by tanaya-bigladder** [comment]
Well, I'll eat crow, for ever thinking that the bug couldn't _possibly_ be in the compiler or libraries... 
There was at least one known bug; described [here](https://developercommunity.visualstudio.com/t/different-printf-double-rounding-behaviour-between/1085732#T-N1211938), and solved [here - 4th bullet point under "Version 2004"](https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b). It was showing up when I isolated [this sprintf](https://github.com/cse-sim/cse/blob/938afeec7c83fde4d3e5a04bce181f5511c2620f/src/CVPAK.CPP#L1044).

In order to properly target Windows 10.0.19041.789, we'll need to upgrade the build to  use SDK version [10.0.20348.0](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). The additional advantage to upgrading the SDK is that 20348 apparently fixes an inconsistency between the Debug and Release libraries, so that now both support the IEEE standard. (This will help when we're going multi-platform.) 

Why did changing the SDK change our results? I think because "[The UCRT [Universal C-Runtime] is now a Windows component, and ships as part of Windows 10 and later.](https://docs.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt?view=msvc-170) " I can't yet explain why changing the compiler version was also affecting regression, though, or why the bug is intermittent.

**Comment by tanaya-bigladder** [comment]
PR #225
